version: "3"
services:
  client:
    build: ./client
    ports:
      - "1234:1234"
    working_dir: /app
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./server:/app
